game_name: "My First Mind Game"
num_games: 5
results_dir: "./results"
agents:
  - type: PerfectAgent
    name: "Perfect Player 1"
  - type: NoisyAgent
    name: "Noisy Player 1"
    params:
      offset: 3
      noise: 1
  - type: RandomAgent
    name: "Random Player 1"
    params:
      min_wait: 10
      max_wait: 50
