game_name: "Three Perfect Players and an LLM"
log_level: "DEBUG"
num_games: 2
results_dir: "./results"
agents:
  - type: PerfectAgent
    name: "Perfect Player 1"
  - type: PerfectAgent
    name: "Perfect Player 2"
  - type: PerfectAgent
    name: "Perfect Player 3"
  - type: LLMAgent
    name: "LLM Player 4"
    model: "deepseek/deepseek-chat-v3-0324:free"