game_name: "Three Perfect Players and an LLM"
log_level: "DEBUG"
num_games: 3
results_dir: "./results"
agents:
  - type: PerfectAgent
    name: "Perfect Player 1"
  - type: PerfectAgent
    name: "Perfect Player 2"
  - type: PerfectAgent
    name: "Perfect Player 3"
  - type: LLMAgent
    name: "LLM Player 4"
    params:
      model_name: "openai/gpt-4.1-nano"
